### ISSUE TITLE
feature details/linkout functionality no longer functioning?

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#103]
not sure of status of code, but just interacting with the version released on peanutbase I was surprised to see that the markers and QTLs only seem to be using a browser dialog to indicate their identities but no further details or options to link to other resources. hopefully a temporary state of affairs, but putting the issue in to formalize the need to get something similar to the old functionality back into place.

**Comment by nathanweeks** [comment]
This sounds like a site-specific (PeanutBase) configuration issue, and not a regression in the cmap-js codebase / functionality? If so, I'll go ahead and close this issue here (please correct me if I'm mistaken & reopen the issue!)
