### ISSUE TITLE
Mithril 2: missing backbone once maps are removed

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/cmap-js#147]
Testing Cmap-JS on Mithril-2-update branch

After removing a map from the screen - the ruler and backbone of the remaining maps are not redrawn. 
<img width="1068" alt="Screenshot 2024-08-22 at 18 55 14" src="https://github.com/user-attachments/assets/7145b334-fc8c-4875-9dc3-4646d2d75bed">

**Comment by That-Thing** [comment]
Fixed
