### ISSUE TITLE
Need to add a GlycineMine link out to QTLs in Cmap-js

### ISSUE THREAD

**Issue by maxglycine** [LegumeFederation/cmap-js#155]
Currently when you click on a QTL in Cmap-js you get a dialog box with a link to SoyBase classic.  We should also include a link to the glycinemine report for the QTL as well.  This way when we decommission classic all we will have to do is remove the classic link.
![Screenshot 2024-11-07 at 3 44 25 PM](https://github.com/user-attachments/assets/ca620274-9933-430c-93a6-e83d813c76df)
@That-Thing @jd-campbell @StevenCannon-USDA

**Comment by That-Thing** [comment]
Added in branch [glycinemine-modal](https://github.com/LegumeFederation/cmap-js/tree/glycinemine-modal)
