### ISSUE TITLE
Add selection state to data model

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#31]
I think @awilkey has started thinking about "rubber-banding" type selection of features from the UI. 
We'll also want to support other forms of selection (e.g. ctrl-click to build up sets of features of interest). Once we have this we'll need to think about options making use of feature sets; one thing that comes to mind would be using an intermine service to make a feature list that can be used in intermine tools. Another thing that could be considered within scope of cmap-js itself would be a tabular view of the selected features (perhaps a synchronized DataTables opportunity here- @ctcncgr has experience with this and might be brought on board to help out if appropriate).

**Comment by nathanweeks** [comment]
@adf-ncgr I think this functionality had been implemented. Could you verify it works as expected in the [cmap-js demo](https://github.com/LegumeFederation/cmap-js) linked to from the README ?

**Comment by adf-ncgr** [comment]
looks like the rubber-banding works, but this issue was really about what to do with feature sets after selection. Currently it pops them up into a list in a dialog but as far as I can tell you can't do anything other than open individual details (note that the links provided are now broken with the move of the targeted pages to "legacy"). That said, I am fine with closing the issue if there's no plan to develop functionality further

**Comment by nathanweeks** [comment]
Thanks for the clarification. The Intermine service seems out-of-scope for cmap-js. The current list-in-a-dialog may not quite qualify as a "tabular view", but at least it provides a facility to see which features are in the rubber-banded area.

Regarding the demo links for legumeinfo.org: those can be updated when there's an appropriate "permanent" service to point to. That's probably a new issue (@Cheehau0659), so I'll go ahead and close this one for now.

**Comment by adf-ncgr** [comment]
@nathanweeks I think both the broken links and the connecting to other services like intermine could be handled by the new linkout component (eventually). We'll demo a first version of it next time we meet and could discuss further whether it's appropriate to try to add to cmap-js
