### ISSUE TITLE
Mouseover popups when no labels displayed?

### ISSUE THREAD

**Issue by ekcannon** [LegumeFederation/cmap-js#33]
Mouseover popup labels for the QTL features in the example would be better than onclick labels. (The latter should probably be used for link menus [https://github.com/ncgr/cmap-js/issues/29]). I see the challenge between making the feature labels readable on the display and creating a readable display with all those labels showing and mouseover popups might be a compromise.

**Comment by adf-ncgr** [comment]
@ekcannon- does the current implementation of the popover address this issue? now installed on legfed-stage/cmap-js if you want to poke it without messing with git updates.

**Comment by adf-ncgr** [comment]
I think the current popover addresses this, but feel free to reopen if I misunderstood
