### ISSUE TITLE
labelling maps in display

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#39]
currently, the only clue as to which map is which is provided by the order in which they are listed in the map removal options. We probably just need to spend a little real estate to add a title of sorts to each map display.

**Comment by awilkey** [comment]
@adf-ncgr This is going to be intergrated with map reordering in https://github.com/ncgr/cmap-js/tree/feature/swap as it seems best to combine map re-ordering with dragging/on mouseover of a feature title.

**Comment by adf-ncgr** [comment]
OK, will try to remember to close this when that branch is in place- thanks!

**Comment by adf-ncgr** [comment]
live instance has this fix- closing
