### ISSUE TITLE
display of text labels in safari is very broken

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#41]
@macgrant6230 pointed this out, and it seems to be easily reproduced if you have access to safari. see the screenshot. seems likely to be some issue with the font we've chosen, but not sure

![image](https://user-images.githubusercontent.com/2009605/27057437-6fec3c5a-4f89-11e7-9152-6b265de4449a.png)

**Comment by awilkey** [comment]
This one is weird, it looks like it may be an issue with downloading the google webfont when first loaded. This is only a guess, as loading a local instance in safari had no issues, and it was only using the external site where the issue made itself  visible, will look into trying to find a reasonable solution of testing if a font is loaded before a draw call.

**Comment by macgrant6230** [comment]
Please send these emails to
  dgrant@iastate.edu
instead of this address

Thanks,
DG

**Comment by adf-ncgr** [comment]
fixed in live version
