### ISSUE TITLE
display of labels on initial view is a sometimes thing

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#42]
Another one from @macgrant6230, who will soon join in the issue reporting fun for himself. 
this one is a little harder to characterize and reproduce (but it is reproducible, as seen in the screenshot below), but basically it seems that in some browsers (the example is using firefox) when the page is initially loaded the text labels appear to be missing, although after some interaction with the view they will appear, and subsequent reloads of the page seem to then appear OK as well.
I seem to be able to reproduce it only by quitting firefox altogether and then loading the intial view into a fresh instance (ie just closing the window and creating a new one fails to give the same behavior).

![image](https://user-images.githubusercontent.com/2009605/27057672-57e3aea8-4f8a-11e7-9201-740ff1a969f0.png)

**Comment by awilkey** [comment]
It is an error with the default css imported from node not catching the nunito addition to the font list in the css, and not catching the fallover fonts (from what I can tell). I think it is solved through commit 83a943045f4052d3d65865dc6a131bdf9b30d597 but haven't fully tested yet.

**Comment by adf-ncgr** [comment]
fixed in live version
