### ISSUE TITLE
accommodating marker-QTL associations

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#53]
this has been on David Grant's wishlist for a while. Although we don't currently have a well-defined way for representing this in the cmap data file, we could certainly adopt a convention; alternatively, we could consider getting the info from auxiliary web-service calls (e.g. we already store this info in the soymine and the query mechanisms ought to be able to serve it up in a web-friendly form).

**Comment by cann0010** [comment]
Closing, because it is not clear to me what association is intended. Since a QTL is an abstraction of a distribution, distinct markers may not be associated. Re-open if this can be described more clearly.
