### ISSUE TITLE
specification of tracks on left and right sides of backbone

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#54]
both the UI and the config file need to be able to support placement of tracks on either side of the backbone, mostly as an aid to comparative contexts in which you don't want the line-drawing to cross the features that represent the main substance of the map content. 

NB: we might want to consider whether track labels should be configurable with respect to whether they render closer or further from the backbone than the glyph that represents them (as opposed to either making the labels always to the right of their bar or always further from the backbone, which would likely be fine for the majority of users)

**Comment by awilkey** [comment]
feature/track-side branch has implemented Left/Right display of data tracks. Flipping ruler and label position is to be held for a different update, as that will require a slight rebuild of the label system as it currently exists.
@adf-ncgr @jd-campbell This should be ready for QA. in addition, it should help fix bug #67

**Comment by adf-ncgr** [comment]
thanks- this will be a nice addition; I'm going to have to recuse myself from QA for the next week or so, hopefully @jd-campbell will have some time or else you can try to get some time from david grant or steven or someone user-like.

**Comment by jd-campbell** [comment]
I will be have time on Monday & Tuesday for QA. =)

**Comment by awilkey** [comment]
It is just display at the moment, so it shouldn't require too much additional testing. Shifting contents via drag will come soon :tm: alongside the changes to allow repositioning of the lables/ruler, but this feels like a task best left to iterate over than try to get done all at once.

**Comment by nathanweeks** [comment]
The changes in the feature/track-side branch are in the master branch, and the track *position* parameter  appears to work as documented when specified in the cmap.json:

https://github.com/LegumeFederation/cmap-js/blob/35212878a66e8eca61c7754e5f25149d0af1cd43/Configuration.md?plain=1#L152

It doesn't seem that changing track position in the user Configuration textarea (#22) works, but the user configuration functionality will likely need to be reworked and tested in its entirety before a cmap-js release, so I'll close this issue.
