### ISSUE TITLE
correspondence drawing should probably be limited to features that are both in view (at least partially)

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/cmap-js#59]
when zoomed, the lines that are drawn to indicate the existence of correspondences between features that are out of the bounds of the view seem to clutter the view without providing any particularly useful information (at least, not that I can think of):

![image](https://user-images.githubusercontent.com/2009605/29885780-3b054e08-8d75-11e7-8a7a-30c57d1a1adc.png)

at the least providing a configuration option to suppress this seems worthwhile (or rather making the default to suppress it and an option to enable it if desired), and probably just making it non optional behavior would be fine.

**Comment by awilkey** [comment]
I've been thinking about this fairly recently (in light of denser maps).
So far, I'm torn between default behavior staying as-is, pruning correspondences that aren't visible on both source and target maps, or returning to behavior that was similar earlier with the first draft of the feature tracks and "cut" any tracks/marks to be even with the top/bottom of the displayed region. 

Its definitely an enhancement that warrants more feedback from actual users.

**Comment by cann0010** [comment]
Resolving this, as I think the fragmentary correspondence lines at high zoom have the advantage of indicating that a correspondence does exist; you just need to change the zoom level to see them.
