### ISSUE TITLE
Change QTL/marker UI needs instructions

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/cmap-js#66]
I kind of understand what to do once I played with the UI a few times but I think for a novel user we need simple instructions on the right side of the box.  Sample instruction write up: 

- To add another QTL/Maker track click the '+' sign
- To change the color click the color box 
- Click apply to ensure the color changes
![screen shot 2017-09-25 at 3 36 19 pm](https://user-images.githubusercontent.com/13021601/30829854-a8897692-a207-11e7-8db3-9cdcd4a5f40c.png)

**Comment by jd-campbell** [comment]
Issue closed. Instructions and tutorials will be generated after completion.

**Comment by nathanweeks** [comment]
@jd-campbell Do you have suggested text for the instructions?

**Comment by jd-campbell** [comment]
My apologies for forgetting about this and thank you for the reminder.  Below is the text that I have written for instructions on this page: 


> To add or change a track to the map:
> - Choose a marker type from the dropdown list
> - Change the Track title which will be present on the map
> - Click on the button with the colored square
> 	- Choose a color for the particular marker type
> 	- Once a color is chosen click apply on the right side of the color panel
> 
> To add more than one marker type to a track:
> - Click on the button with the "+"  
> Choose the marker type from the dropdown list
> - Click on the button with the colored square
> 	- Choose a color for the particular marker type
> 	- Once a color is chosen click apply on the right side of the color panel
> 	
> Once the track is configured with one or more marker types click on "APPLY SELECTION" button on the screen 
> The new configured track will be drawn on the map.

**Comment by jd-campbell** [comment]
Review and closed
