### ISSUE TITLE
Weird div layout on the last map in the series

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/cmap-js#67]
This issue may be fixed by the new UI layout. One the last map on "D1a gm_composite" the QTL/maker div seems to be on top of the map track.  
![screen shot 2017-09-25 at 3 43 15 pm](https://user-images.githubusercontent.com/13021601/30830151-9c276e58-a208-11e7-88e6-e585980dfeec.png)
![screen shot 2017-09-25 at 3 42 40 pm](https://user-images.githubusercontent.com/13021601/30830152-9c289d32-a208-11e7-8aff-d31934892c41.png)
![screen shot 2017-09-25 at 3 41 04 pm](https://user-images.githubusercontent.com/13021601/30830153-9c2dedd2-a208-11e7-8050-cd2bcfa696ad.png)

**Comment by nathanweeks** [comment]
@jd-campbell I think this issue had been resolved in the master branch, but feel free to reopen if you still notice a problem.
