### ISSUE TITLE
Different QTL/Maker color change bottom 

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/cmap-js#68]
Currently the button to click if I want to change the QTL/maker color has this tiny square of color on it.  I think it would be better if the button was entirely that one color instead of a tiny square of color. 
![screen shot 2017-09-25 at 3 54 20 pm](https://user-images.githubusercontent.com/13021601/30830603-22bfa01a-a20a-11e7-9e36-4a8b6ce14f5d.png)
![screen shot 2017-09-25 at 3 54 29 pm](https://user-images.githubusercontent.com/13021601/30830601-22ba90c0-a20a-11e7-949d-270fd96201b5.png)

**Comment by nathanweeks** [comment]
@Cheehau0659: what do you think about 6065f315500121aac5ee4044f5b6142870251b9b?

**Comment by Cheehau0659** [comment]
I think this is a better way of doing it.

**Comment by jd-campbell** [comment]
Fixed.
