### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by awilkey** [LegumeFederation/cmap-js#73]
Rework UI to have a cleaner visual style and to have more consistent behavior across elements.

**Comment by awilkey** [comment]
https://github.com/LegumeFederation/cmap-js/commit/9225024dca46688287b324377236829e18f73ba2 is ready for other people to test and comment on behavior.

**Comment by adf-ncgr** [comment]
thanks! will have a look soon. have a great weekend...

**Comment by awilkey** [comment]
Have noticed some odd behavior when adding/removing map sets, will fix before submitting for merge.

**Comment by nathanweeks** [comment]
Commit 9225024dca46688287b324377236829e18f73ba2 is in the master branch.
