### ISSUE TITLE
adding/removing maps not clearing previous config

### ISSUE THREAD

**Issue by bradfordcondon** [LegumeFederation/cmap-js#83]
Trying to add or remove maps causes the plots to be redrawn, but without clearing the old one, resulting in a dogpile of plots on the left end ( see image at bottom).  This is with the example dataset.

I'm getting a lot of this flavor of error

```
mithril.js:816 Uncaught TypeError: Cannot read property 'parentNode' of null
    at removeNodeFromDOM (mithril.js:816)
    at continuation (mithril.js:803)
    at removeNode (mithril.js:794)
    at updateNode (mithril.js:635)
    at updateNodes (mithril.js:537)
    at Object.render (mithril.js:983)
    at run0 (mithril.js:1046)
    at Array.<anonymous> (mithril.js:1000)
    at Object.redraw (mithril.js:1028)
    at Function.mount (mithril.js:1049)
```

I've followed the config guide ( submodule installs, `npm install`,  `npm run watch`)

![screen shot 2018-04-16 at 3 25 27 pm](https://user-images.githubusercontent.com/7063154/38830502-8c9a2440-418a-11e8-9337-d5a162516651.png)

**Comment by awilkey** [comment]
I do believe this is related to a similar issue I've been trying to work around where a node on the vdom doesn't properly propagate the change to the associated data in some cases after rearranging by drag. Will add checking for this issue alongside the fixes for that.

**Comment by awilkey** [comment]
Fix should be in place with commit  https://github.com/LegumeFederation/cmap-js/commit/d7e98ff93eb929c823e801965d2dc79d7b91501e Will subject it to some testing before merging into the master branch.

**Comment by bradfordcondon** [comment]
Hi @awilkey 
Sorry I'm still experiencing this issue on current master branch.

**Comment by bradfordcondon** [comment]
apologies, i just didnt understand your git flow.  issue is resolved on developer branch.
