### ISSUE TITLE
Failed to resolve initialView entry

### ISSUE THREAD

**Issue by almasaeed2010** [LegumeFederation/cmap-js#88]
Hello,

On a new clone of the master branch, we get the following error:

```
AppModel.js:93 failed to resolve initialView entry: {"source":"pv_consensus","map":"Pv02","tracks":[{"type":"qtl","title":"seed 1","filters":["QTL_root","QTL_seed","QTL_other-seed"],"fillColor":["yellow"]},{"type":"qtl","filters":["QTL_seed","QTL_root"],"fillColor":["green","red"]}]}
```

We followed the steps by cloning, initializing git submodules and running `npm run watch`.

Any idea what this means?

Thanks!

**Comment by awilkey** [comment]
Do you get the same issue if you pull the develop branch?

**Comment by almasaeed2010** [comment]
Yep that's the master branch.

**Comment by awilkey** [comment]
I'm checking now. Getting similar results on a fresh copy, but not an old one, so suspecting that a node package may have updated and broken compatibility. Will update when I have more information.

**Comment by awilkey** [comment]
After inspecting, the issue lies in papaparse. While I work on a fix, a temp workaround is:
`npm uninstall papaparse` 
followed by
 `npm install papaparse@4.2.0`
Somewhere along the path between 4.4 and 4.2 something broke with how we were using the package.

**Comment by awilkey** [comment]
It looks like the default behavior for an empty header field changed slightly, but it should be working now if you pull from the master branch.

**Comment by almasaeed2010** [comment]
Thanks @awilkey for fixing it so promptly! I will test it soon and let you know.

**Comment by almasaeed2010** [comment]
Yep works perfectly. Thanks again!

**Comment by awilkey** [comment]
No problem! I am glad that this issue is near to some changes I've been playing with for a standalone electron version of cmap-js, so it was just a matter of finding out *where* in the chain things were breaking instead of a blind search for a place to start. Do feel free to open any more issues for bugs or enhancement requests!

**Comment by almasaeed2010** [comment]
Electorn version sounds pretty cool! Looking forward to checking it out. 

And will do! We are currently (@bcondon and I) working on a module to make this an easy install on Tripal and chado so we'll come her for any questions/issues.

Thanks!
