### ISSUE TITLE
headers dont scale with map image

### ISSUE THREAD

**Issue by bradfordcondon** [LegumeFederation/cmap-js#91]
Zooming out scales the image, but not the header.  See:

<img width="1438" alt="screen shot 2018-05-11 at 10 36 02 am" src="https://user-images.githubusercontent.com/7063154/39929950-6b199aae-5507-11e8-88e1-7c32eb4edc82.png">

I've added a bunch to the initial config because I cant add remove  via the interface doesnt work still:  https://github.com/LegumeFederation/cmap-js/issues/83

**Comment by awilkey** [comment]
This is a known 'bug' that hasn't been addressed due to questions at to the usefulness of zooming out. It is sort of a torn issue between zoom being useful for large map sets, but can be annoying to work around with smaller ones. 

I haven't put a fix in place, as the system that allows for dragging the titles to re-arrange is slated for a re-work so a similar system can be put in place for any tracks added to the mapsets.

Any opinions on this behavior are welcome.

**Comment by bradfordcondon** [comment]
I agree zooming out just isnt very helpful since the user wont be able to make ou the marker names.  I do wish there was a way to reduce the real estate each map takes up. 

I think the ability to configure map arrangement might be nice.  So I could specify that im going to have  6 maps in a 2x3 arrangement, for example.

Finally I'm afraid the add/remove map UI is going to be confusing for our users.  What might be more intuitive is if the admin can specify the number and arrangement of maps to view.  The user can then press a dropdown button in the header to change what map is displayed in that view port.  Alternatively we may implement this viewer in a way where the user selects which chromosome to view in hte Drupal interface, and it loads the cmap js with just that map as an option...

**Comment by mestato** [comment]
I agree the zoom out in this case (ie. zoom in and out on the whole group of maps) isn't very useful. And its a bit confusing, as it leaves the map name headers (Chinese Chestnut Genetic Map A, in example above) in the same place and the same size. The zoom in/out on the map itself, changing the scale, is useful.

**Comment by awilkey** [comment]
I agree the map name header scales not keeping does make it more confusing, but the amount of work to change it was always slightly more work than it was worth before making the decision to keep the feature or not.

**Comment by awilkey** [comment]
After the current develop branch is merged and a new tag issued, the next branch will trial removal of the whole view zoom settings.

**Comment by awilkey** [comment]
Experimental branch with disabled whole map zoom with commit https://github.com/LegumeFederation/cmap-js/commit/e35466c8afc913fc7c585130b6e0f051312cc5a3
