### ISSUE TITLE
manually adding a second track just alters both new and old track

### ISSUE THREAD

**Issue by bradfordcondon** [LegumeFederation/cmap-js#92]
I have SNP and microsatellite markers.  I press + on the right site, add microsat in red to the right.
<img width="524" alt="screen shot 2018-05-11 at 10 44 50 am" src="https://user-images.githubusercontent.com/7063154/39930353-7eec8eaa-5508-11e8-9637-f4740e51908c.png">

OK, great.  I then press the + on the left side of the map.  I add the SNP markers, in green.

<img width="550" alt="screen shot 2018-05-11 at 10 45 06 am" src="https://user-images.githubusercontent.com/7063154/39930355-80a4f124-5508-11e8-890d-b1d9d74374c4.png">

Now I have two snp marker tracks on the left in red.

**Comment by awilkey** [comment]
Is this the fulll steps to reproduce? I can't think offhand what would lead to this behavior, but I will take a look into it.

**Comment by awilkey** [comment]
Out of curiosity, can you replicate the behavior on the default configuration on the "gm_genome glyma.Chr01" track (track 3)?

**Comment by bradfordcondon** [comment]
yes!  exactly as described above.

**Comment by awilkey** [comment]
Ok, I think I know *exactly* what's breaking. I should have a patch ready this afternoon.

**Comment by bradfordcondon** [comment]
Great, thank you!


Semi related question, how can these tracks be pre-defined in the configuration json?  The documentation says track types are only for QTL and manhattan but clearly marker works too?

**Comment by awilkey** [comment]
QTL is a bit of a minsomer from early development. Markers are drawn as a QTL track, but the format is set with a minimum height to account for markers and other one-dimensional data points that may need to be displayed off the map backbone.

**Comment by awilkey** [comment]
Could you pull the `bugfix/trackdup` and check to see if the behavior persists? I think it should be fixed, but would like a second set of eyes.

**Comment by bradfordcondon** [comment]
This is the results of first adding snp tracks on left as red, and then adding synteny tracks on right as blue

<img width="975" alt="screen shot 2018-05-11 at 2 41 38 pm" src="https://user-images.githubusercontent.com/7063154/39941093-7897faaa-5529-11e8-9f1a-10b064dad883.png">

**Comment by awilkey** [comment]
I just tried the exact same thing, and didn't have an issue off the same branch (though there are some definite issues with the really long labels I need to look into...)

![screen shot 2018-05-11 at 13 48 05](https://user-images.githubusercontent.com/7633989/39941385-041e73c2-5522-11e8-955e-2ff309d5360d.png)

**Comment by bradfordcondon** [comment]
are you scrolling to the right to get to the third map or removing?  I'm having complicating issues with scrolling and the brown linking lines that may be contributing to the problem...

**Comment by bradfordcondon** [comment]
yes scrollign in the alpha warning box does help a lot.

OK I also was not hitting "apply" in the color change box.

<img width="1307" alt="screen shot 2018-05-11 at 2 59 18 pm" src="https://user-images.githubusercontent.com/7063154/39941882-ee8a678c-552b-11e8-82f7-54c9b7213b01.png">


So I guess the issue is resolved, thank you

**Comment by awilkey** [comment]
Good! I'll merge the patch directly into both master and develop and close, as it is a simple enough fix.
