### ISSUE TITLE
Reset button behavior

### ISSUE THREAD

**Issue by awilkey** [LegumeFederation/cmap-js#93]
Working on cleaning up some loose ends before the next release, and a question that has been hanging since the beginning is in a place to be revisited.

How should the refresh/reset button work? Currently it (mostly) moves the view back to having the first map back at (0,0) and resets any whole mapset zoom, which is sort of useful if you get too lost.

There is an argument for also having it reset the scale zoom on the individual maps, but an alternative exists in it doing a complete reset and bringing the view back to the original configuration.

Open to suggestions on how to proceed with this, including any other behaviors not mentioned.

**Comment by ekcannon** [comment]
Removed reset button (for now)
